---
- name: Installera Apache2, flask och nödvändiga paket
  apt:
    name:
      - apache2
      - libapache2-mod-wsgi-py3 # viktigt för att Apache ska kunna köra Python/Flask
      - python3-flask
      - python3-psycopg2 # krävs för att Python ska kunna prata med PostgreSQL
    state: present
    update_cache: yes # köra apt-get update innan installation

- name: Skapa en mapp för chatt-appen
  file:
  # vi lägger chatt koden en egen mapp.
  # för att sepparera koden från apaches standard mapp så att strukturen blir tydligare.
    path: /var/www/chatt
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: skapa mapp för HTML-mallar
  file:
  # Flask vill ha HTML-filer i en undermapp
  # som måste, heta templates (inte samma som templates som i den delade mappen).
    path: /var/www/chatt/templates
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: kopiera in python kod (app.py) från template
  template:
  # vi använder templates för att kunna skicka in
  #lösenord etc som variabler
    src: app.py.j2
    dest: /var/www/chatt/app.py
    owner: www-data
    group: www-data
    mode: '0644'
  notify: restart apache # triggar handlern om filen ändras

- name: Kopiera in WSGI-konfigurationen
  template:
    src: app.wsgi.j2
    dest: /var/www/chatt/app.wsgi
    owner: www-data
    group: www-data
    mode: '0644'
  notify: restart apache

- name: Kopiera in chattens HTML-sida
  template:
    src: index.html.j2
    dest: /var/www/chatt/templates/index.html
    owner: www-data
    group: www-data
    mode: '0644'
  notify: restart apache

- name: Kopiera in Apaches VirtualHost-konfiguration
  template:
    src: apache-vhost.conf.j2
    dest: /etc/apache2/sites-available/webbserver.conf
  notify: restart apache

- name: Aktivera den nya webbserver-konfigurationen
  command: a2ensite webbserver.conf
  # args-klausulen nedan gör modulen idempotent.
  # kommandot körs inte igen om filen redan är länkad, vilket sparar tid och undviker fel.
  args:
    creates: /etc/apache2/sites-enabled/webbserver.conf
  notify: restart apache

- name: Inaktivera Apaches default-sida
  command: a2dissite 000-default.conf
  args:
    removes: /etc/apache2/sites-enabled/000-default.conf
  notify: restart apache

- name: Driftsätt health check-skriptet för övervakning
  template:
    src: health.py.j2
    dest: /usr/local/bin/health.py
    owner: root
    group: root
    mode: '0755' # 0755 gör att skriptet blir exekverbart i Linux

- name: Säkerställ att Apache2 är igång och aktiverad vid boot
  service: 
    name: apache2
    state: started
    enabled: yes