---
#Dessa kommandon körs som vanliga tasks men enbart om de triggas av "notify". 

#Stoppar och startar om Nginx helt (Kortare avbrott)
- name: restart nginx
  service: 
    name: nginx
    state: restarted

#Laddar om konfigurationen utan avbrott (Används i produktion)
- name: reload nginx
  service: 
    name: nginx
    state: reloaded


#Tasks i denna fil körs alltid sist.