# I ansible inventory så beskriver olika grupper av servrar och deras IP-adresser.
# för att ansible vet vart den ska ansluta och köra playbooks.
[loadbalancer]
lb ansible_host=192.168.56.10

[webservers]
web1 ansible_host=192.168.56.11 
web2 ansible_host=192.168.56.12 

# vi lägger till ansible_connection=local så att ansible vet att det är här ifrån.
# det gör så att den inte försöker ansluta till sig själv via SSH utan kör sin playbook direkt
[database]
db ansible_host=192.168.56.13 ansible_connection=local